version: '3.9'
services:
  bpcl-api:
    image: bpcl/bpcl-api:0.0.1
    ports:
      - target: 3300
        protocol: tcp
        published: 3300
        mode: ingress
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      NODE_ENV: 'production'
    volumes:
      - api_data:/usr/src/app/uploads
      - /home/ubuntu/dockerapps/bpclblockchain/fabric-samples/test-network/organizations:/config
    networks:
      backend:
volumes:
  api_data:
 
networks:
  backend:
    driver: overlay
    attachable: true